### PR TITLE
Logic bug fixed which caused applyContentFilter to trigger all the time

### PR DESCRIPTION
**Pull request by tvhdev**
Corrected small error where plugin did its magic thru applyContentFilter on the post content even when the posttype was not eligible or the widget was inactive

### CODE REVIEW

**Comment by tvhdev** [comment]
The bug screwed up Impreza's fancy grid layout functionality!

**Comment by shazahm1** [comment]
I ended up reverting this change in 22f2b9c85098110c3cb473d87154e4f072c063a7 because then the sidebar widget no longer functioned.

**Comment by tvhdev** [comment]
Hello,OK,i understand. We will need to look for another solution then. Best regardsAm 24.01.2020 20:38 schrieb "Steven A. Zahm" <notifications@github.com>:I ended up reverting this change in 22f2b9c because then the sidebar widget no longer functioned.

**Comment by shazahm1** [comment]
Couple questions...

- Did you have the TOC widget in any sidebar at all, even if that sidebar was not used on the page?
- Do you recall what `$is_eligible` value was and `is_active_widget()` return value was.

**Comment by tvhdev** [comment]
Hello, the page with the TOC widget is https://www.ess-kempfle.de/wissenswertes/ratgeber/stromspeicher/. A page which the widget used to interfere with (here the said theme's grid layout) is https://www.ess-kempfle.de/referenzen/photovoltaik/ there's no toc code though (quick search for "toc" returns nothing) it is only configured for the "stromspeicher" page (checkbox)

**Comment by tvhdev** [comment]
For the variables "$is_eligible" and "is_active...." i will have to check on the site and get back to you. One of them wasnt true, which one is the question:)

**Comment by shazahm1** [comment]
ok, `is_active_widget()` should always return true since it is in a sidebar. `$is_eligible` will depend in settings.

**Pull request closed without merging**
